steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
      'build', 
      '--cache-from',
      'eu.gcr.io/$PROJECT_ID/autosuggest-catalog:latest',
      '--build-arg',
      'BUILDTIME_GIT_TAG=$TAG_NAME',
      '-f' , './Dockerfile', 
      '--tag=eu.gcr.io/$PROJECT_ID/autosuggest-catalog:$TAG_NAME', 
      '.' 
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'eu.gcr.io/$PROJECT_ID/autosuggest-catalog:$TAG_NAME', 'eu.gcr.io/$PROJECT_ID/autosuggest-catalog:latest' ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'patch'
      - 'deployment'
      - 'autosuggest-catalog-deployment'
      - '-n'
      - 'autosuggest-dev'
      - '-o'
      - 'yaml'
      - '-p'
      - |
        spec:
          template:
            spec:
              containers:
                - name: autosuggest-catalog
                  image: eu.gcr.io/$PROJECT_ID/autosuggest-catalog:$TAG_NAME
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autosuggest-cluster-eu'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', '--project=$PROJECT_ID', '--zone=us-central1-a', 'autosuggest-cluster-us']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'patch'
      - 'deployment'
      - 'autosuggest-catalog-deployment'
      - '-n'
      - 'autosuggest-dev'
      - '-o'
      - 'yaml'
      - '-p'
      - |
        spec:
          template:
            spec:
              containers:
                - name: autosuggest-catalog
                  image: eu.gcr.io/$PROJECT_ID/autosuggest-catalog:$TAG_NAME
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autosuggest-cluster-us'

images:
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-catalog:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/autosuggest-catalog:latest'
